### ISSUE TITLE
请问如何让捆绑运行完后不删除自身?

### ISSUE THREAD

**Issue by AllCheeks** [Yihsiwei/GoFileBinder#2]
XD

**Comment by Yihsiwei** [comment]
'''panfu := selfile[0:2]
		if !strings.Contains(selfile, "C:") {
	
			dstFile = panfu + "\\Yihsiwei.DAT"
		} else {
			dstFile = panfu + dstFile
		}
		os.Rename(selfile, dstFile)'''
将以上代码删除掉
